name: flutter_login_facebook_ntt
description: Login via Facebook. Easily add Facebook login feature in your application. User profile information included.
version: 1.0.0
homepage: https://github.com/nttra83/flutter_login_facebook
repository: https://github.com/nttra83/flutter_login_facebook
issue_tracker: https://github.com/nttra83/flutter_login_facebook/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  list_ext: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ntt.flutter_login_facebook_ntt
        pluginClass: FlutterLoginFacebookPlugin
      ios:
        pluginClass: FlutterLoginFacebookPlugin
